image: debian:sid

build:
	stage: build-linux-x64
	before_script:
		- sh scripts/gitlab_linux_pre.sh
	script:
		- sh scripts/gitlab_linux.sh

	stage: build-mingw64-win64
	before_script:
		- sh scripts/gitlab_mingw_pre.sh
	script:
		- sh scripts/gitlab_mingw.sh
