image: debian:sid

build-linux-x64:
        stage: build
        before_script:
                - sh scripts/gitlab_linux_pre.sh
        script:
                - sh scripts/gitlab_linux.sh

build-mingw64-x64:
        stage: build
        before_script:
                - sh scripts/gitlab_mingw_pre.sh
        script:
                - sh scripts/gitlab_mingw.sh
